<a href="https://colab.research.google.com/github/JCentercreation/Google-Colaboratory/blob/main/LearningTensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.3.0


In [ ]:
import tensorflow as tf
print(tf.__version__)
print(tf.test.is_gpu_available())
print(tf.config.list_physical_devices('GPU'))
from tensorflow import keras
print(tf.keras.__version__)

2.3.0
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
True
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
2.4.0


In [4]:
import numpy as np
x = np.array(8)
print(x)
print(x.ndim)  #Dimension del tensor
print(x.shape)  #Forma(shape) del tensor: el numero de dimensiones por eje
print(x.size)
print(x.dtype)  #Tipo de datos almacenado en el tensor

8
0
()
1
int64


In [7]:
#Veamos ahora un vector (tensor 1D)
x = np.array([2, 8, 3, 2])
print(x)
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

[2 8 3 2]
1
(4,)
4
int64


In [9]:
#Veamos ahora una matriz (tensor 2D)
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9
int64


In [11]:
#Veamos ahora un tensor 3D
x = np.array([[[1, 2],[3, 4]],[[5, 6],[7, 8]]])
print(x)
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)
8
int64
